apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: gke-demo-test-pra
spec:
  name: gke-demo-test-pra
  documentation: Updates the a given component service for the gke-demo-test fleet to a new chart version for any stage
  updates:
    regexReplacements:
    - regex: "version: (.*) # VERSION"
      file: fleets/gke-demo-test/{{context.component }}/{{ context.pipeline.stage.name }}.yaml
      replacement: "version: {{ context.version }} # VERSION"
  scmConnectionRef:
    name: plural
  title: Updating {{ context.component }} {{ context.pipeline.stage.name }} helm version to {{ context.version }} (stage={{ context.pipeline.stage.name }})
  message: Updating {{ context.component }} {{ context.pipeline.stage.name }} helm version to {{ context.version }} (stage={{ context.pipeline.stage.name }})
  identifier: pluralsh/fleet
  configuration:
  - name: component
    type: STRING
    documentation: The component to update
  - name: version
    type: STRING
    documentation: The helm chart version to use